version: '3.8'

services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb,s3
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "./localstack:/var/lib/localstack"
  app:
    build: .
    environment:
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    command: sh -c "python -m unittest discover -s tests -p '*.py'"
    depends_on:
      - localstack